### ISSUE TITLE
React-Redux-Group Project Setup

### ISSUE THREAD

**Issue by apt2tell** [apt2tell/react-redux-group-project#25]
## Setup for the group project

https://github.com/Okechukwu-muokwugwo/react-redux-group-project/projects/1

In this group, we are 2 Team members

**Comment by Davidosky007** [comment]
Hi @Okechukwu-muokwugwo @j-tee 👋, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
* All necessary information about the team members was provided 👍 
* Link to project correct 👍  
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
